services:
  - type: web
    name: connect-headscale
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./headscale/Dockerfile
    dockerContext: .
    autoDeployTrigger: commit
    healthCheckPath: /health
