services:
  - type: web
    name: connect-headscale
    runtime: docker
    plan: starter
    region: oregon
    dockerfilePath: ./headscale/Dockerfile
    dockerContext: .
    autoDeployTrigger: commit
    healthCheckPath: /health
    disk:
      name: headscale-data
      mountPath: /var/lib/headscale
      sizeGB: 1
